/* Generate a list of 10000000 (ten million) random numbers with C++. Use the Binary Search 
and the Interpolation Search to find a key. Measure and report the execution time for each 
search. */

#include <iostream>
#include <vector>
#include <algorithm>
#include <chrono>
#include <random>

// Function for binary search
int binarySearch(const std::vector<int>& arr, int key){ // this line defines a function named binarySearch that takes a constant reference to a vector of int and an int key as its parameters.
    // The function returns an int value, which represents the index of the key in the vector if found, or -1 if not found.
    int left = 0; 
    int right = arr.size() - 1; // this line declares an int variable right and initializes it to the last index of the vector arr by using the size() member function and subtracting 1.

    while (left <= right) { //starts a loop that continues as long as left is less than or equal to right, which means there are still elements to search within the defined range.
        int mid = left + (right - left) / 2; // this line calculates the middle index mid by taking the average of left and right. 
        //This is done to avoid potential overflow issues that can arise when calculating (left + right) directly.

        if (arr[mid] == key) { // this line checks if the element at index mid in the vector arr is equal to the key we are searching for. If it is, we have found the key.
            return mid; 
        }
        else if (arr[mid] < key) { // this line checks if the element at index mid is less than the key. If it is, it means that the key must be located in the right half of the current search range.
            left = mid + 1; // if arr[mid] is less than key, this line updates left to be mid + 1, effectively narrowing down the search range to the right half of the current range.
        }
        else { // if arr[mid] is greater than key, it means that the key must be located in the left half of the current search range.
            right = mid - 1; // this line updates right to be mid - 1, effectively narrowing down the search range to the left half of the current range.
        }
    }
    return -1; // if we exit the while loop without finding the key, this line returns -1 to indicate that the key was not found in the vector.
}

// Function for interpolation search
int interpolationSearch(const std::vector<int>& arr, int key){
    int low = 0;
    int high = arr.size() - 1; // this line declares an int variable high and initializes it to the last index of the vector arr by using the size() member function and subtracting 1.

    while (low <= high && key >= arr[low] && key <= arr[high]){
        if (low == high) { // this line checks if low is equal to high, which means there is only one element left in the search range.
            if (arr[low] == key) { // if the single remaining element at index low is equal to the key, we have found the key.
                return low; 
            }
            return -1; // if the single remaining element is not equal to the key, this line returns -1 to indicate that the key was not found.
        }
        // evita division by zero
        if(arr[high] == arr[low]){
            if (arr[low] == key){
                return low;
            }
            return -1; // if the values at high and low are the same, we cannot calculate the position using interpolation. In this case, we check if the value at low is equal to the key. If it is, we return low; otherwise, we return -1 to indicate that the key was not found.
        }
        long long pos = low + ((long long)(key - arr[low]) * (high - low)) / (arr[high] - arr[low]); // this line calculates the position pos using the interpolation formula.

        if (arr[pos] == key){
            return pos;
        }
        if (arr[pos] < key)
        {
            low = pos + 1;
        }
        else
        {
            high = pos - 1;
        }
    }
    return -1; // if the key is not found, return -1
}


int main(){
    const int N = 10000000; 
    std::vector<int> arr(N); // this line declares a vector of int named arr with a size of N, which will be used to store the randomly generated numbers.

    // Generate random numbers
    std::mt19937 rng(std::random_device{}()); // this line creates a random number generator object named rng using the Mersenne Twister algorithm. The random_device is used to seed the generator with a non-deterministic random value.
    std::uniform_int_distribution<int> dist(1, 10000000); // this

    std::cout << "Generating random numbers..." << std::endl;
    for (int i =0; i<N; i++){
        arr[i] = dist(rng); // this line fills the vector arr with random integers generated by the dist distribution using the rng generator.
    }

    std::cout << "Sorting the array..." << std::endl;
    std::sort(arr.begin(), arr.end()); // this line sorts the vector arr in ascending order using the sort function from the algorithm library, which takes two iterators as arguments (the beginning and end of the vector).

    // Choose a random key from the array to search for
    int key = arr[N /2]; // this line selects a random key from the array by taking the element at the middle index (N / 2) of the sorted vector arr.
    std::cout << "Searching for key: " << key << std::endl;

    //Binary Search timing
    auto start1 = std::chrono::high_resolution_clock::now(); // this line captures the current time point before starting the binary search using the high_resolution_clock from the chrono library.
    int pos1 = binarySearch(arr, key); // this line calls the binarySearch function with the sorted vector arr and the key to search for, and stores the returned index in the variable pos1.
    auto end1 = std::chrono::high_resolution_clock::now(); // this line captures the current time point after the binary search has completed.
    //auto duration1 = duration_cast<std::chrono::microseconds>(end1 - start1);
    auto duration1 = std::chrono::duration_cast<std::chrono::microseconds>(end1 - start1); // this line calculates the duration of the binary search by taking the difference between end1 and start1, and converting it to microseconds using the duration_cast function from the chrono library.

    // Interpolation Search timing
    auto start2 = std::chrono::high_resolution_clock::now(); // this line captures the current time point before starting the interpolation search.
    int pos2 = interpolationSearch(arr, key); // this line calls the interpolationSearch function with the sorted vector arr and the key to search for, and stores the returned index in the variable pos2.
    auto end2 = std::chrono::high_resolution_clock::now(); // this line captures
    //auto duration2 = duration_cast<std::chrono::microseconds>(end2 - start2); // this line calculates the duration of the interpolation search by taking the difference between end2 and start2, and converting it to microseconds using the duration_cast function.
    auto duration2 = std::chrono::duration_cast<std::chrono::microseconds>(end2 - start2); // this line calculates the duration of the interpolation search by taking the difference between end2 and start2, and converting it to microseconds using the duration_cast function from the chrono library.
    
    std::cout<<"\n Binary Search:\n";
    std::cout <<"Position: "<<pos1 <<std::endl;
    std::cout <<"Execution time: "<<duration1.count() << " microseconds\n";

    std::cout<<"\n Interpolation Search:\n";
    std::cout <<"Position: "<<pos2 <<std::endl;
    std::cout <<"Execution time: "<<duration2.count() << " microseconds\n";

    return 0;
}